### ISSUE TITLE
[Improvement] Direct "Login with Apple"

### ISSUE THREAD

**Issue by codingalex** [magiclabs/magic-ios-pod#11]
When implemented, the "Login with Apple" button open a popup with a webview and then the Apple login popup appears. It would be great to have a more native implementation and remove the webview in the login process.
Thus, Magic Apple login method gets called -> Apple Login Popup

**Comment by Ethella** [comment]
It's great feedback! Unfortunately, it's something we're not considering at the moment due to our infrastructure, the blank web page has been used to authenticate the Magic layer.
