### ISSUE TITLE
Crash: dyld: dyld cache load error: shared cache file open() failed dyld: Symbol not found

### ISSUE THREAD

**Issue by kishanraja** [magiclabs/magic-ios-pod#20]
**Issue Description**

After adding the MagicSDK pod and run the app, the application gets crashes with the bellow crash log. This crash happens with the latest versions 2.2.1 and 2.2.0.

**Crash Log**
```
dyld: dyld cache load error: shared cache file open() failed
dyld: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: /Users/appdeveloper/Library/Developer/CoreSimulator/Devices/3AB65244-F53C-475D-8857-8F150635EE78/data/Containers/Bundle/Application/2DC78AB9-B909-4533-9D67-D3DAA9A51350/MagicSDK-Demo.app/Frameworks/MagicSDK.framework/MagicSDK
  Expected in: /Users/appdeveloper/Library/Developer/CoreSimulator/Devices/3AB65244-F53C-475D-8857-8F150635EE78/data/Containers/Bundle/Application/2DC78AB9-B909-4533-9D67-D3DAA9A51350/MagicSDK-Demo.app/Frameworks/PromiseKit.framework/PromiseKit
 in /Users/appdeveloper/Library/Developer/CoreSimulator/Devices/3AB65244-F53C-475D-8857-8F150635EE78/data/Containers/Bundle/Application/2DC78AB9-B909-4533-9D67-D3DAA9A51350/MagicSDK-Demo.app/Frameworks/MagicSDK.framework/MagicSDK
dyld: launch, loading dependent libraries
```

**Podfile**

```
target 'MagicSDK-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MagicSDK-Demo
  pod 'MagicSDK'
  
  # Required for XCFramework
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
```

**Environment**
Xcode Version: 12.3 and 12.5
Swift Version: 5.3
Platform(s) running : iOS 14.3
macOS version running Xcode: intel - macOS Big Sur 11.1

**Comment by Ethella** [comment]
Hi @kishanraja, I tried to reproduce it, but I'm not able to.

Could you try to do `shift+k` to clear the cache and reinstall the pods? Plz let me know if the error persists. 😄

**Comment by kishanraja** [comment]
Hello, @Ethella Thanks for looking at this. 

I have tried this many times and create a new 2 - 3 fresh project but not solved. I just install the pod and run the app.

Here I attached a demo project link that might be helpful: https://github.com/kishanraja/MagicDemo.git

For now, I'm using the old version of SDK (v2.1.2) but it will also give us an error during the send transaction process 

: Magic-SDK Error: DecodingError.typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "response", intValue: nil), CodingKeys(stringValue: "error", intValue: nil), CodingKeys(stringValue: "code", intValue: nil)], debugDescription: "Expected to decode Int but found a number instead.", underlyingError: nil)) (code 4864)

let me know if you need more info.

Thank you.

**Comment by Ethella** [comment]
Taking a look right at your repo now.

For the decoding issue, we are currently working on it.

**Comment by Ethella** [comment]
@kishanraja I tried a couple of times to reproduce it but it still comes with no luck. And I also try to find relevant issues on the internet and I found no positive results. 

Unfortunately, I guess I'll have to punt this issue and see if anyone else has encountered the same issue and fill in more context to help triage it.

**Comment by kishanraja** [comment]
@Ethella  Thank you for checking this. I will try my side to find more context and will update you. If possible can you please sare the environment like build architectures and Xcode version etc. so I can try to run the project on that environment. Or is there any external setting required for the build settings?

**Comment by Ethella** [comment]
> @Ethella Thank you for checking this. I will try my side to find more context and will update you. If possible can you please sare the environment like build architectures and Xcode version etc. so I can try to run the project on that environment. Or is there any external setting required for the build settings?

There's no more external configuration or build architectures required other than the ones listed in the doc. 
```
Pod 1.10.1
Xcode 12.5 (12E262)
Big Sur 11.4

swiftc -version
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.5.0
```

**Comment by kishanraja** [comment]
Thanks, @Ethella.  Your information helped me. After updating Xcode from 12.3 to Xcode 12.5.1, it works fine.

**Comment by Ethella** [comment]
> Thanks, @Ethella. Your information helped me. After updating Xcode from 12.3 to Xcode 12.5.1, it works fine.

Glad it helps! 😄
