### ISSUE TITLE
Undefined symbol: protocol witness table for MagicSDK.RpcProvider : MagicSDK_Web3.Web3Provider in MagicSDK

### ISSUE THREAD

**Issue by gorevoy** [magiclabs/magic-ios-pod#22]
<img width="1383" alt="Screenshot 2021-06-25 at 14 22 53" src="https://user-images.githubusercontent.com/2830063/123417807-e9ed1d00-d5c0-11eb-9977-10ce78ec565e.png">

Building on device (iPhone 11 Pro).
Tried:
1) Exclude arm64 architecture.
2) Clean archs in "Run Script" in Build Phases.
3) Clean, restart, delete Derived data, haha...

Mac M1, Xcode 12.5.

By the way building on Simulator don't work too...

So there's no way to try your product 🤷‍♂️ 😢

**Comment by Ethella** [comment]
Hey @gorevoy, just checking to see if the issue still exists. We've migrated to XCFramework and I think that might solve your issue here. Lmk if the issue is still there after installing the latest version
