### ISSUE TITLE
Symbol Not Found

### ISSUE THREAD

**Issue by Reality-Dev** [magiclabs/magic-ios-pod#24]
I am trying to install this pod into an iOS project.
I added `pod 'MagicSDK'` to my pod file and ran `pod install`. The pods appear to install but when I run the project the app terminates and I get this error:
```
dyld[12907]: Symbol not found: _$s13MagicSDK_Web30C8ProviderP4send7request8responseyAA10RPCRequestVyqd__G_yAA0C8ResponseVyqd_0_GctSeRd__SERd__SeRd_0_SERd_0_r0_lFTq
  Referenced from: /private/var/containers/Bundle/Application/DE96CB79-CB1A-426D-8F78-AEC8EB6BC925/Test Magic Pod.app/Frameworks/MagicSDK.framework/MagicSDK
  Expected in: /private/var/containers/Bundle/Application/DE96CB79-CB1A-426D-8F78-AEC8EB6BC925/Test Magic Pod.app/Frameworks/MagicSDK_Web3.framework/MagicSDK_Web3
```
I made a new project with just the default demo app code (that just puts "Hello World" on screen) to make sure it was nothing in my project causing the issue. The same exact error occurred. I tried uninstalling the pod and using `pod 'MagicSDK', '2.3.0'` and `pod 'MagicSDK', '~> 2.3.0'` but both had the same issue.

**Comment by Reality-Dev** [comment]
By looking into the [demo app's](https://github.com/magiclabs/magic-ios-demo) pod file, I found the solution.
While the readMe for this repository states:
```
To install it, simply add the following line to your Podfile:
`pod 'MagicSDK'
```
As I mentioned in the original issue, this did not work for me.
What _did_ work is placing this code in the pod file. My target's name is `Test Magic Pod`
```
# Pod imports
def importPods
    
    # Distributed Library on Cocoapods
    pod 'MagicSDK', '~> 2.3'
    pod 'MagicExt-OAuth', '~> 0.10'

end

use_frameworks!
# iOS pod setup
target ‘Test Magic Pod' do
  platform :ios, '9.0'
  importPods

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SKIP_INSTALL'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
```
If this solution is necessary to fix this issue, then please update the readMe to indicate that simply using `pod 'MagicSDK'` will not work.

**Comment by Ethella** [comment]
Thx for the advice! I'll update the READ.me to reflect the latest changes.

You may also check https://magic.link/docs/login-methods/email/integration/ios for integration tutorial.
