### ISSUE TITLE
Issue when compiling

### ISSUE THREAD

**Issue by codingalex** [magiclabs/magic-ios-pod#7]
- Installed MagicSDK via Cocoapods
- iOS Target SDK: 14.0

Getting the following error:
"Compiling for iOS 8.0, but module 'CryptoSwift' has a minimum deployment target of iOS 9.0"

**Comment by Ethella** [comment]
Hi @codingalex 

You may add this code snippet to the end of your file to eliminate the error. 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
   
    # overwrite web3 packages to change deployment target to 9.0
    if ['Web3'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.3'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
```

A breaking version will be released to resolve the issue later on. Please let me know if you have any issue after adding this code snippet

**Comment by codingalex** [comment]
Thanks! I added the code to the Podfile but when importing the SDK, I get the following error:
`Failed to build module 'MagicSDK' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced`

**Comment by Ethella** [comment]
Just release a version of `2.0.0`. Could you try it out? Please reply in this thread if it still doesn't work for you.

**Comment by codingalex** [comment]
That fixed the issue. Thanks a lot!
